// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: termbridge/cloud/v1/cloud.proto

package cloudv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	EmailVerified bool                   `protobuf:"varint,4,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_termbridge_cloud_v1_cloud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_termbridge_cloud_v1_cloud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_termbridge_cloud_v1_cloud_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

type DeviceSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Online        bool                   `protobuf:"varint,3,opt,name=online,proto3" json:"online,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ConnectedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceSummary) Reset() {
	*x = DeviceSummary{}
	mi := &file_termbridge_cloud_v1_cloud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceSummary) ProtoMessage() {}

func (x *DeviceSummary) ProtoReflect() protoreflect.Message {
	mi := &file_termbridge_cloud_v1_cloud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceSummary.ProtoReflect.Descriptor instead.
func (*DeviceSummary) Descriptor() ([]byte, []int) {
	return file_termbridge_cloud_v1_cloud_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeviceSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceSummary) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *DeviceSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeviceSummary) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

func (x *DeviceSummary) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

type CloudSessionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GateUrl       string                 `protobuf:"bytes,1,opt,name=gate_url,json=gateUrl,proto3" json:"gate_url,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceName    string                 `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	ConnectedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudSessionSummary) Reset() {
	*x = CloudSessionSummary{}
	mi := &file_termbridge_cloud_v1_cloud_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudSessionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudSessionSummary) ProtoMessage() {}

func (x *CloudSessionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_termbridge_cloud_v1_cloud_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudSessionSummary.ProtoReflect.Descriptor instead.
func (*CloudSessionSummary) Descriptor() ([]byte, []int) {
	return file_termbridge_cloud_v1_cloud_proto_rawDescGZIP(), []int{2}
}

func (x *CloudSessionSummary) GetGateUrl() string {
	if x != nil {
		return x.GateUrl
	}
	return ""
}

func (x *CloudSessionSummary) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CloudSessionSummary) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *CloudSessionSummary) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

type AuthLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthLoginReq) Reset() {
	*x = AuthLoginReq{}
	mi := &file_termbridge_cloud_v1_cloud_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthLoginReq) ProtoMessage() {}

func (x *AuthLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_termbridge_cloud_v1_cloud_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthLoginReq.ProtoReflect.Descriptor instead.
func (*AuthLoginReq) Descriptor() ([]byte, []int) {
	return file_termbridge_cloud_v1_cloud_proto_rawDescGZIP(), []int{3}
}

func (x *AuthLoginReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthLoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type TokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResp) Reset() {
	*x = TokenResp{}
	mi := &file_termbridge_cloud_v1_cloud_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResp) ProtoMessage() {}

func (x *TokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_termbridge_cloud_v1_cloud_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResp.ProtoReflect.Descriptor instead.
func (*TokenResp) Descriptor() ([]byte, []int) {
	return file_termbridge_cloud_v1_cloud_proto_rawDescGZIP(), []int{4}
}

func (x *TokenResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenResp) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

type AuthMeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authenticated bool                   `protobuf:"varint,1,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	CloudSession  *CloudSessionSummary   `protobuf:"bytes,4,opt,name=cloud_session,json=cloudSession,proto3" json:"cloud_session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthMeResp) Reset() {
	*x = AuthMeResp{}
	mi := &file_termbridge_cloud_v1_cloud_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthMeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthMeResp) ProtoMessage() {}

func (x *AuthMeResp) ProtoReflect() protoreflect.Message {
	mi := &file_termbridge_cloud_v1_cloud_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthMeResp.ProtoReflect.Descriptor instead.
func (*AuthMeResp) Descriptor() ([]byte, []int) {
	return file_termbridge_cloud_v1_cloud_proto_rawDescGZIP(), []int{5}
}

func (x *AuthMeResp) GetAuthenticated() bool {
	if x != nil {
		return x.Authenticated
	}
	return false
}

func (x *AuthMeResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthMeResp) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AuthMeResp) GetCloudSession() *CloudSessionSummary {
	if x != nil {
		return x.CloudSession
	}
	return nil
}

type ListDevicesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DeviceSummary       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResp) Reset() {
	*x = ListDevicesResp{}
	mi := &file_termbridge_cloud_v1_cloud_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResp) ProtoMessage() {}

func (x *ListDevicesResp) ProtoReflect() protoreflect.Message {
	mi := &file_termbridge_cloud_v1_cloud_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResp.ProtoReflect.Descriptor instead.
func (*ListDevicesResp) Descriptor() ([]byte, []int) {
	return file_termbridge_cloud_v1_cloud_proto_rawDescGZIP(), []int{6}
}

func (x *ListDevicesResp) GetItems() []*DeviceSummary {
	if x != nil {
		return x.Items
	}
	return nil
}

type CurrentDeviceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PublicKey     string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentDeviceReq) Reset() {
	*x = CurrentDeviceReq{}
	mi := &file_termbridge_cloud_v1_cloud_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentDeviceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentDeviceReq) ProtoMessage() {}

func (x *CurrentDeviceReq) ProtoReflect() protoreflect.Message {
	mi := &file_termbridge_cloud_v1_cloud_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentDeviceReq.ProtoReflect.Descriptor instead.
func (*CurrentDeviceReq) Descriptor() ([]byte, []int) {
	return file_termbridge_cloud_v1_cloud_proto_rawDescGZIP(), []int{7}
}

func (x *CurrentDeviceReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CurrentDeviceReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CurrentDeviceReq) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type CurrentDeviceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Device        *DeviceSummary         `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentDeviceResp) Reset() {
	*x = CurrentDeviceResp{}
	mi := &file_termbridge_cloud_v1_cloud_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentDeviceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentDeviceResp) ProtoMessage() {}

func (x *CurrentDeviceResp) ProtoReflect() protoreflect.Message {
	mi := &file_termbridge_cloud_v1_cloud_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentDeviceResp.ProtoReflect.Descriptor instead.
func (*CurrentDeviceResp) Descriptor() ([]byte, []int) {
	return file_termbridge_cloud_v1_cloud_proto_rawDescGZIP(), []int{8}
}

func (x *CurrentDeviceResp) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *CurrentDeviceResp) GetDevice() *DeviceSummary {
	if x != nil {
		return x.Device
	}
	return nil
}

type CloudOAuthStartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorizeUrl  string                 `protobuf:"bytes,1,opt,name=authorize_url,json=authorizeUrl,proto3" json:"authorize_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudOAuthStartResp) Reset() {
	*x = CloudOAuthStartResp{}
	mi := &file_termbridge_cloud_v1_cloud_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudOAuthStartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudOAuthStartResp) ProtoMessage() {}

func (x *CloudOAuthStartResp) ProtoReflect() protoreflect.Message {
	mi := &file_termbridge_cloud_v1_cloud_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudOAuthStartResp.ProtoReflect.Descriptor instead.
func (*CloudOAuthStartResp) Descriptor() ([]byte, []int) {
	return file_termbridge_cloud_v1_cloud_proto_rawDescGZIP(), []int{9}
}

func (x *CloudOAuthStartResp) GetAuthorizeUrl() string {
	if x != nil {
		return x.AuthorizeUrl
	}
	return ""
}

type CloudOAuthAuthorizeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RedirectUrl   string                 `protobuf:"bytes,1,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudOAuthAuthorizeResp) Reset() {
	*x = CloudOAuthAuthorizeResp{}
	mi := &file_termbridge_cloud_v1_cloud_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudOAuthAuthorizeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudOAuthAuthorizeResp) ProtoMessage() {}

func (x *CloudOAuthAuthorizeResp) ProtoReflect() protoreflect.Message {
	mi := &file_termbridge_cloud_v1_cloud_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudOAuthAuthorizeResp.ProtoReflect.Descriptor instead.
func (*CloudOAuthAuthorizeResp) Descriptor() ([]byte, []int) {
	return file_termbridge_cloud_v1_cloud_proto_rawDescGZIP(), []int{10}
}

func (x *CloudOAuthAuthorizeResp) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

type CloudOAuthExchangeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudOAuthExchangeReq) Reset() {
	*x = CloudOAuthExchangeReq{}
	mi := &file_termbridge_cloud_v1_cloud_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudOAuthExchangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudOAuthExchangeReq) ProtoMessage() {}

func (x *CloudOAuthExchangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_termbridge_cloud_v1_cloud_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudOAuthExchangeReq.ProtoReflect.Descriptor instead.
func (*CloudOAuthExchangeReq) Descriptor() ([]byte, []int) {
	return file_termbridge_cloud_v1_cloud_proto_rawDescGZIP(), []int{11}
}

func (x *CloudOAuthExchangeReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type CloudOAuthCallbackReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudOAuthCallbackReq) Reset() {
	*x = CloudOAuthCallbackReq{}
	mi := &file_termbridge_cloud_v1_cloud_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudOAuthCallbackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudOAuthCallbackReq) ProtoMessage() {}

func (x *CloudOAuthCallbackReq) ProtoReflect() protoreflect.Message {
	mi := &file_termbridge_cloud_v1_cloud_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudOAuthCallbackReq.ProtoReflect.Descriptor instead.
func (*CloudOAuthCallbackReq) Descriptor() ([]byte, []int) {
	return file_termbridge_cloud_v1_cloud_proto_rawDescGZIP(), []int{12}
}

func (x *CloudOAuthCallbackReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CloudOAuthCallbackReq) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type CloudOAuthCallbackResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CloudSession  *CloudSessionSummary   `protobuf:"bytes,1,opt,name=cloud_session,json=cloudSession,proto3" json:"cloud_session,omitempty"`
	Redirect      string                 `protobuf:"bytes,2,opt,name=redirect,proto3" json:"redirect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudOAuthCallbackResp) Reset() {
	*x = CloudOAuthCallbackResp{}
	mi := &file_termbridge_cloud_v1_cloud_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudOAuthCallbackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudOAuthCallbackResp) ProtoMessage() {}

func (x *CloudOAuthCallbackResp) ProtoReflect() protoreflect.Message {
	mi := &file_termbridge_cloud_v1_cloud_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudOAuthCallbackResp.ProtoReflect.Descriptor instead.
func (*CloudOAuthCallbackResp) Descriptor() ([]byte, []int) {
	return file_termbridge_cloud_v1_cloud_proto_rawDescGZIP(), []int{13}
}

func (x *CloudOAuthCallbackResp) GetCloudSession() *CloudSessionSummary {
	if x != nil {
		return x.CloudSession
	}
	return nil
}

func (x *CloudOAuthCallbackResp) GetRedirect() string {
	if x != nil {
		return x.Redirect
	}
	return ""
}

var File_termbridge_cloud_v1_cloud_proto protoreflect.FileDescriptor

const file_termbridge_cloud_v1_cloud_proto_rawDesc = "" +
	"\n" +
	"\x1ftermbridge/cloud/v1/cloud.proto\x12\x13termbridge.cloud.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"v\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12%\n" +
	"\x0eemail_verified\x18\x04 \x01(\bR\remailVerified\"\xdb\x01\n" +
	"\rDeviceSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06online\x18\x03 \x01(\bR\x06online\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12=\n" +
	"\fconnected_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt\x127\n" +
	"\tlast_seen\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\"\xad\x01\n" +
	"\x13CloudSessionSummary\x12\x19\n" +
	"\bgate_url\x18\x01 \x01(\tR\agateUrl\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\x12=\n" +
	"\fconnected_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt\"\\\n" +
	"\fAuthLoginReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"M\n" +
	"\tTokenResp\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\"\xcc\x01\n" +
	"\n" +
	"AuthMeResp\x12$\n" +
	"\rauthenticated\x18\x01 \x01(\bR\rauthenticated\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12-\n" +
	"\x04user\x18\x03 \x01(\v2\x19.termbridge.cloud.v1.UserR\x04user\x12M\n" +
	"\rcloud_session\x18\x04 \x01(\v2(.termbridge.cloud.v1.CloudSessionSummaryR\fcloudSession\"K\n" +
	"\x0fListDevicesResp\x128\n" +
	"\x05items\x18\x01 \x03(\v2\".termbridge.cloud.v1.DeviceSummaryR\x05items\"U\n" +
	"\x10CurrentDeviceReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\"k\n" +
	"\x11CurrentDeviceResp\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12:\n" +
	"\x06device\x18\x02 \x01(\v2\".termbridge.cloud.v1.DeviceSummaryR\x06device\":\n" +
	"\x13CloudOAuthStartResp\x12#\n" +
	"\rauthorize_url\x18\x01 \x01(\tR\fauthorizeUrl\"<\n" +
	"\x17CloudOAuthAuthorizeResp\x12!\n" +
	"\fredirect_url\x18\x01 \x01(\tR\vredirectUrl\"+\n" +
	"\x15CloudOAuthExchangeReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"A\n" +
	"\x15CloudOAuthCallbackReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"\x83\x01\n" +
	"\x16CloudOAuthCallbackResp\x12M\n" +
	"\rcloud_session\x18\x01 \x01(\v2(.termbridge.cloud.v1.CloudSessionSummaryR\fcloudSession\x12\x1a\n" +
	"\bredirect\x18\x02 \x01(\tR\bredirectBEZCtermbridge-go/internal/shared/dto/proto/termbridge/cloud/v1;cloudv1b\x06proto3"

var (
	file_termbridge_cloud_v1_cloud_proto_rawDescOnce sync.Once
	file_termbridge_cloud_v1_cloud_proto_rawDescData []byte
)

func file_termbridge_cloud_v1_cloud_proto_rawDescGZIP() []byte {
	file_termbridge_cloud_v1_cloud_proto_rawDescOnce.Do(func() {
		file_termbridge_cloud_v1_cloud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_termbridge_cloud_v1_cloud_proto_rawDesc), len(file_termbridge_cloud_v1_cloud_proto_rawDesc)))
	})
	return file_termbridge_cloud_v1_cloud_proto_rawDescData
}

var file_termbridge_cloud_v1_cloud_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_termbridge_cloud_v1_cloud_proto_goTypes = []any{
	(*User)(nil),                    // 0: termbridge.cloud.v1.User
	(*DeviceSummary)(nil),           // 1: termbridge.cloud.v1.DeviceSummary
	(*CloudSessionSummary)(nil),     // 2: termbridge.cloud.v1.CloudSessionSummary
	(*AuthLoginReq)(nil),            // 3: termbridge.cloud.v1.AuthLoginReq
	(*TokenResp)(nil),               // 4: termbridge.cloud.v1.TokenResp
	(*AuthMeResp)(nil),              // 5: termbridge.cloud.v1.AuthMeResp
	(*ListDevicesResp)(nil),         // 6: termbridge.cloud.v1.ListDevicesResp
	(*CurrentDeviceReq)(nil),        // 7: termbridge.cloud.v1.CurrentDeviceReq
	(*CurrentDeviceResp)(nil),       // 8: termbridge.cloud.v1.CurrentDeviceResp
	(*CloudOAuthStartResp)(nil),     // 9: termbridge.cloud.v1.CloudOAuthStartResp
	(*CloudOAuthAuthorizeResp)(nil), // 10: termbridge.cloud.v1.CloudOAuthAuthorizeResp
	(*CloudOAuthExchangeReq)(nil),   // 11: termbridge.cloud.v1.CloudOAuthExchangeReq
	(*CloudOAuthCallbackReq)(nil),   // 12: termbridge.cloud.v1.CloudOAuthCallbackReq
	(*CloudOAuthCallbackResp)(nil),  // 13: termbridge.cloud.v1.CloudOAuthCallbackResp
	(*timestamppb.Timestamp)(nil),   // 14: google.protobuf.Timestamp
}
var file_termbridge_cloud_v1_cloud_proto_depIdxs = []int32{
	14, // 0: termbridge.cloud.v1.DeviceSummary.connected_at:type_name -> google.protobuf.Timestamp
	14, // 1: termbridge.cloud.v1.DeviceSummary.last_seen:type_name -> google.protobuf.Timestamp
	14, // 2: termbridge.cloud.v1.CloudSessionSummary.connected_at:type_name -> google.protobuf.Timestamp
	0,  // 3: termbridge.cloud.v1.AuthMeResp.user:type_name -> termbridge.cloud.v1.User
	2,  // 4: termbridge.cloud.v1.AuthMeResp.cloud_session:type_name -> termbridge.cloud.v1.CloudSessionSummary
	1,  // 5: termbridge.cloud.v1.ListDevicesResp.items:type_name -> termbridge.cloud.v1.DeviceSummary
	1,  // 6: termbridge.cloud.v1.CurrentDeviceResp.device:type_name -> termbridge.cloud.v1.DeviceSummary
	2,  // 7: termbridge.cloud.v1.CloudOAuthCallbackResp.cloud_session:type_name -> termbridge.cloud.v1.CloudSessionSummary
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_termbridge_cloud_v1_cloud_proto_init() }
func file_termbridge_cloud_v1_cloud_proto_init() {
	if File_termbridge_cloud_v1_cloud_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_termbridge_cloud_v1_cloud_proto_rawDesc), len(file_termbridge_cloud_v1_cloud_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_termbridge_cloud_v1_cloud_proto_goTypes,
		DependencyIndexes: file_termbridge_cloud_v1_cloud_proto_depIdxs,
		MessageInfos:      file_termbridge_cloud_v1_cloud_proto_msgTypes,
	}.Build()
	File_termbridge_cloud_v1_cloud_proto = out.File
	file_termbridge_cloud_v1_cloud_proto_goTypes = nil
	file_termbridge_cloud_v1_cloud_proto_depIdxs = nil
}
